AddLocationForm:

<AddLocationForm>:
    orientation: "vertical"
    search_input: search_box
    search_results: search_results_list
    BoxLayout:
	    height: "40dp"
        size_hint_y: None
        TextInput:
	        size_hint_x: 50
	        id: search_box
	    Button:
		    text: "Search"
		    size_hint_x: 25
		    on_press: root.search_location()
	    Button:
		    text: "Current Location"
		    size_hint_x: 25
    ListView:
	    id: search_results_list
	    item_strings: []
